apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::439647921196:role/mfe-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-08T02:03:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "766"
  uid: 5f1733e7-741d-40ab-9a72-95547111bc77
